### ISSUE TITLE
Right justification breaks when 'number' is enabled

### ISSUE THREAD

**Issue by m1foley** [simplenote-vim/simplenote.vim#108]
When`%>` is included in `g:SimplenoteNoteFormat` (which is the default behavior) it doesn't right-justify properly when the `number` option is enabled.

`set number` is in my vimrc, and when I execute `:SimplenoteList` the lines extend offscreen by 5 characters or so. `:set nonumber` fixes the formatting.

**Comment by atomicules** [comment]
This feels vaguely familiar. Like I've come across this myself and perhaps decided to live with it and/or decided it couldn't be fixed... not sure. Will try to take a look soon.

I think I know what you mean though.

**Comment by atomicules** [comment]
Ah yeah, I mentioned that on this commit: https://github.com/mrtazz/simplenote.vim/commit/f7debaf1cf6fc7fd1b771ee9278829b07cf4b0e9

> This doesn't account for the Vim configuration setting of numberwidth,
but I'm not sure if it should.

Will take a look at this again.

**Comment by atomicules** [comment]
I've got a fix for this. Going to push it and a new release once https://github.com/simplenote-vim/simplenote.py/pull/27 is all sorted and merged in as well.

**Comment by atomicules** [comment]
Ok, change of plan, pushed a fix for this now since the simplenote.py changes are going to take longer than I thought.
