### ISSUE TITLE
SimplenoteOpen does not evaluate input

### ISSUE THREAD

**Issue by Andrea-Augello** [simplenote-vim/simplenote.vim#112]
With the new Simplenote update it is now possible to use internal links. To make use of that feature, I tried to build a custom command that yanks the id in the link, and then calls `SimplenoteOpen @"`. However (adding a print inside the python function) I discovered that the @" is used verbatim, even if vim.eval() is called on the function argument.

Is there any way to do something like that? I have no experience in developing vim plugins, but if you can give me some pointers I am available to try and implement this functionality myself and open a pull request. Thank you for your time.

**Comment by Andrea-Augello** [comment]
Update: I managed to cobble up this function that goes to the next Simplenote internal link, yanks the note id, and opens the note in a new split, restoring the previous content of the yank buffer. 
I added it to my simplenote.vim file and it seems to work fine. I'll open a pull request.
 
`		function! SimplenoteGoFun()
			let temp = @"
			norm /simplenote://t)yiw
			let noteid = @"
			let @"=temp
			echo noteid
			call simplenote#SimplenoteOpen(noteid)
		endfunction
		command! -nargs=0 SimplenoteGo :call SimplenoteGoFun()
`

**Comment by atomicules** [comment]
I'm closing this on on the basis that https://github.com/simplenote-vim/simplenote.vim/pull/113 has been merged in. If I'm missing something else though please re-open.
