### ISSUE TITLE
Support for NeoVim / Vim 8 Async api

### ISSUE THREAD

**Issue by smarquez1** [simplenote-vim/simplenote.vim#66]
This plugin is amazing, good job!
Any plans for adapting it to NeoVim's async api?

Thanks

**Comment by atomicules** [comment]
I develop on NetBSD. I see there is a pkgsrc/wip package for Neovim, 
but I haven't yet tried it to see if it works (the package looks 
fairly active though so I guess should work). 

So... I haven't even tried to run Neovim yet, I have no idea about the 
async api, but I do have Neovim on my radar and was planning to see 
how Simplenote.vim functioned under it at some point.

No plans right now, but happy to leave this issue open for when I get 
around to it.
